### ISSUE TITLE
Python is not compatibile

### ISSUE THREAD

**Issue by GabriFrz** [NilSilva/simklExporter#1]
After setting up the scrypt the cmd tells me that python is not compatibile for my windows version. Any tips?

**Comment by NilSilva** [comment]
Post OS version, python version and a print of the console with the error and the command you are using. When I have some time I'll look into it.

**Comment by GabriFrz** [comment]
okay I think I solved that issue but now i got this error:

Microsoft Windows [Version 10.0.22621.2428]

C:\Users\Gabriele\Desktop\simklExporter-main>py simklExporter.py
Traceback (most recent call last):
  File "C:\Users\Gabriele\Desktop\simklExporter-main\simklExporter.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\Users\Gabriele\Desktop\simklExporter-main>

**Comment by NilSilva** [comment]
You probably haven't installed the requests module. 

Try this: 
https://stackoverflow.com/a/17309309

**Comment by GabriFrz** [comment]
Okay it worked but now it gives me this error:

C:\Users\Gabriele\Desktop\simklExporter-main>py simklExporter.py
Traceback (most recent call last):
  File "C:\Users\Gabriele\Desktop\simklExporter-main\simklExporter.py", line 30, in <module>
    user_code = pin_request['user_code']
                ~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'user_code'

sorry for bothering you btw

**Comment by NilSilva** [comment]
Read the readme file. Did you add your client id to the conf.ini file?

**Comment by GabriFrz** [comment]
yes of course

**Comment by GabriFrz** [comment]
okay wait now it actually worked, didn't know that i was supposed to delete the >s lol

**Comment by NilSilva** [comment]
Cool. Everything should be fine because it has tmdb and imdb ids but I recommend taking a quick look because this was something I quickly threw together and I didn't worry to much about doing it super well... I'm closing the issue.
